---
knit: (function(inputFile, encoding) { 
      out_dir <- 'results/tables';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(here::here(),
                        out_dir, 'gene_table.html')) })
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(here)
library(tidyverse)
library(kableExtra)
library(readxl)
source(here('scripts/utils/backbone_params-graphs.R'))
source(here('scripts/utils/backbone_functions.R'))
source(here('scripts/utils/params_biogem.R'))


genes <- c("coxL", "rbcL I", "pufM", "pufL", "PR blue", "PR green (M105)",
           'PR green (L105)', "psbA", "tauA", "phnD", "phnM", "pstS",
           "phoX", "phoD", "ppx", "ppk1", "plcP", "narB",
           "nasA",  "amoA", "ureC", "dmdA", 'fecA')

descriptions <- read_xlsx(here('results/gene_info/database_genes.xlsx')) %>% 
  filter(gene_name %in% genes)
ab.raw <- read_rds(here('data/04_table_gen/abtblraw_all.rds'))
annot <- read_rds(here('data/intermediate_files/annotation.rds')) %>% 
  filter(genename %in% unique(ab.raw$genename))
rich.trend <- read_tsv(here('data/intermediate_files/richness_gene_trends.tsv'))
  
lomb <- readRDS(here('data/intermediate_files/genes_seasonality_test.rds'))
genes.seasonal <- readRDS(here('data/intermediate_files/genes_seasonal.rds')) %>% 
  pull(genename)

```


```{r message=FALSE, warning=FALSE, include=FALSE}
# Calculating the richness summary
richness.summ <- rich.trend %>% 
  select(gene_name, sample, richness) %>% 
  group_by(gene_name) %>% 
  filter(!is.na(gene_name)) %>% 
  summarize( `Median richness` = median(richness),
             `Q25 richness` = quantile(richness)[2],
             `Q75 richness` = quantile(richness)[4]) %>% 
  mutate_if(.predicate = is.double, .funs = round, digits = 1)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Calculating the n of variants for each category

nvariants.df <- annot %>% 
  mutate(evaluated = ifelse(genename %in% lomb$genename, TRUE, FALSE)) %>% 
  mutate(seasonal = ifelse(genename %in% genes.seasonal, TRUE, FALSE)) %>% 
  group_by(gene_name, evaluated, seasonal) %>% 
  summarise( n.variants = n()) %>% 
  group_by(gene_name) %>% 
  mutate(`total variants` = sum(n.variants)) %>% 
  filter(evaluated) %>% 
  mutate(`total evaluated` = sum(n.variants)) %>% 
  filter(seasonal) %>% 
  rename('seasonal variants' = n.variants) %>% 
  select(-seasonal, -evaluated) %>% 
  select(1,3,4,2) %>% 
  mutate(perc_sea = (`seasonal variants` * 100 / `total evaluated`) %>% 
           round(digits = 1))
```


```{r message=FALSE, warning=FALSE, include=FALSE}

# Joining everything

table <- descriptions %>% 
  filter(gene_name %in% genes) %>% 
  mutate(annotation = ifelse( str_detect(annotation, 'PR'), 'MicRhoDE db',
                              annotation)) %>% 
  select(gene_name, `gene long name`, `basic function`, annotation) %>% 
  left_join(nvariants.df, by = 'gene_name') %>% 
  left_join(richness.summ, by = 'gene_name') %>% 
  mutate(gene_name = factor(gene_name, levels = gene.order)) %>% 
  arrange(gene_name) %>% 
  mutate(gene_name = text_spec(gene_name %>% as.character(),
                               italic = ifelse(gene_name %in% gene.italics.sel,
                                               TRUE, 
                                               FALSE)))

```

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Printing da table 
# Adding a total
func <- function(z) if (is.numeric(z)) sum(z) else '' 
sumrow <- as_tibble(lapply(table, func)) %>% 
  mutate(perc_sea = ((`seasonal variants` * 100) / `total evaluated`) %>% 
           round(digits = 1))

# Give name to the first element of the new data frame created above
sumrow[1] <- "Total"
sumrow[9] <- ''
sumrow[10] <- ''
sumrow[11] <- ''

# Add the original and new data frames together
table <- rbind(table, sumrow) %>% 
  rename( "Percentage seasonal (%)" = perc_sea)


colnames(table) <- colnames(table) %>% 
  str_replace("_", " ") %>% 
  str_remove("gene ") %>% 
  str_to_title()

table$Name <- ifelse(
  table$Name == 'Total',
  cell_spec(table$Name, bold = T),
  table$Name)

kbl(table, booktabs = TRUE, escape = FALSE )  %>% 
  kable_styling(full_width = T,
                bootstrap_options = 'striped',
                latex_options = 'striped') %>% 
  pack_rows('Carbon cycle', 1,9) %>% 
  pack_rows('Nitrogen cycle', 10,13) %>% 
  pack_rows('Phosporous cycle', 14,21) %>% 
  pack_rows('Other', 22,23)
  
```


